[general]
static=yes
writeprotect=no
clearglobalvars=no


[arm112]
exten => s,1,NoOp(ARM-112 attempt=${ARM112_ATTEMPT_ID} op=${ARM112_OPERATOR})
 same => n,Stasis(arm_voip,${ARM112_ATTEMPT_ID},${ARM112_OPERATOR})
 same => n,Hangup()

exten => 600,1,Answer()
 same => n,Echo()
 same => n,Hangup()

exten => 601,1,Answer()
 same => n,Playback(demo-congrats)
 same => n,Hangup()

exten => i,1,Hangup()
exten => h,1,NoOp(call finished)
