[global]
type=global
user_agent=ARM112-Asterisk

[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060

[1001]
type=endpoint
context=arm112
disallow=all
allow=ulaw
allow=alaw
auth=1001-auth
aors=1001

[1001-auth]
type=auth
auth_type=userpass
username=1001
password=test

[1001]
type=aor
max_contacts=1
remove_existing=yes