from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '451ea7e8d705'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_templates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', 'version', name='uq_card_templates_code_version')
    )
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.create_index('uq_card_templates_active_code', ['code'], unique=True, postgresql_where=sa.text('is_active'))

    op.create_table('incident_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('service_code', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['incident_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('incident_categories', schema=None) as batch_op:
        batch_op.create_index('ix_incident_categories_parent_id', ['parent_id'], unique=False)
        batch_op.create_index('ix_incident_categories_service_code', ['service_code'], unique=False)

    op.create_table('permissions',
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('roles',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("level IN ('debug', 'info', 'warning', 'error', 'critical')", name='ck_system_events_level'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.create_index('ix_system_events_component_level', ['component', 'level'], unique=False)
        batch_op.create_index('ix_system_events_ts', ['ts'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('permission_code', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['permission_code'], ['permissions.code'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.SmallInteger(), nullable=False),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sa.String(length=64), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.SmallInteger(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_is_active', ['is_active'], unique=False)
        batch_op.create_index('ix_users_role_id', ['role_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('component', sa.String(length=64), nullable=False),
    sa.Column('severity', sa.Enum('INFO', 'WARNING', 'CRITICAL', name='alert_severity'), nullable=False),
    sa.Column('status', sa.Enum('OPEN', 'ACKNOWLEDGED', 'RESOLVED', name='alert_status'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('fingerprint', sa.String(length=128), nullable=False),
    sa.Column('occurrences', sa.Integer(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('acknowledged_by', sa.UUID(), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['acknowledged_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_last_seen_at', ['last_seen_at'], unique=False)
        batch_op.create_index('ix_alerts_status_severity', ['status', 'severity'], unique=False)
        batch_op.create_index('uq_alerts_open_fingerprint', ['fingerprint'], unique=True, postgresql_where=sa.text("status <> 'RESOLVED'"))

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('role_code', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('object_type', sa.String(length=64), nullable=True),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_log_action', ['action'], unique=False)
        batch_op.create_index('ix_audit_log_object', ['object_type', 'object_id'], unique=False)
        batch_op.create_index('ix_audit_log_ts', ['ts'], unique=False)
        batch_op.create_index('ix_audit_log_user_ts', ['user_id', 'ts'], unique=False)

    op.create_table('backups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('is_automatic', sa.Boolean(), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.CheckConstraint("status IN ('running', 'success', 'failed')", name='ck_backups_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.create_index('ix_backups_started_at', ['started_at'], unique=False)

    op.create_table('grading_profiles',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('max_content_errors', sa.SmallInteger(), nullable=False),
    sa.Column('max_grammar_errors', sa.SmallInteger(), nullable=False),
    sa.Column('max_procedure_errors', sa.SmallInteger(), nullable=False),
    sa.Column('max_missing_fields', sa.SmallInteger(), nullable=False),
    sa.Column('default_time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('time_overrun_tolerance_pct', sa.SmallInteger(), nullable=False),
    sa.Column('pass_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('grammar_check_enabled', sa.Boolean(), nullable=False),
    sa.Column('syntax_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('error_weights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('pass_score >= 0 AND pass_score <= 100', name='ck_grading_profiles_pass_score'),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('grading_profiles', schema=None) as batch_op:
        batch_op.create_index('ix_grading_profiles_owner_id', ['owner_id'], unique=False)
        batch_op.create_index('uq_grading_profiles_single_default', ['is_default'], unique=True, postgresql_where=sa.text('is_default'))

    op.create_table('groups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.create_index('ix_groups_teacher_id', ['teacher_id'], unique=False)

    op.create_table('materials',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=64), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('checksum', sa.String(length=128), nullable=True),
    sa.Column('version', sa.SmallInteger(), nullable=False),
    sa.Column('is_indexed', sa.Boolean(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.create_index('ix_materials_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_materials_is_indexed', ['is_indexed'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=128), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index('ix_refresh_tokens_expires_at', ['expires_at'], unique=False)
        batch_op.create_index('ix_refresh_tokens_user_id', ['user_id'], unique=False)

    op.create_table('system_settings',
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('scope', sa.Enum('VOIP', 'BACKUP', 'LOGGING', 'SECURITY', 'PERFORMANCE', 'AI', 'UI', name='setting_scope'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_secret', sa.Boolean(), nullable=False),
    sa.Column('requires_restart', sa.Boolean(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('key')
    )
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.create_index('ix_system_settings_scope', ['scope'], unique=False)

    op.create_table('user_service_scope',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'category_id')
    )
    with op.batch_alter_table('user_service_scope', schema=None) as batch_op:
        batch_op.create_index('ix_user_service_scope_category_id', ['category_id'], unique=False)

    op.create_table('group_members',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.create_index('ix_group_members_user_id', ['user_id'], unique=False)

    op.create_table('scenarios',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('difficulty', sa.SmallInteger(), nullable=False),
    sa.Column('origin', sa.Enum('MANUAL', 'AI', 'IMPORTED', 'STUDENT', name='scenario_origin'), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING_REVIEW', 'PARTIALLY_VALIDATED', 'VALIDATED', 'ARCHIVED', name='scenario_status'), nullable=False),
    sa.Column('legend', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_card', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reference_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('grading_profile_id', sa.UUID(), nullable=True),
    sa.Column('source_attempt_id', sa.UUID(), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('validated_by', sa.UUID(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('validated_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('difficulty BETWEEN 1 AND 5', name='ck_scenarios_difficulty'),
    sa.CheckConstraint('time_limit_sec > 0', name='ck_scenarios_time_limit'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ),
    sa.ForeignKeyConstraint(['grading_profile_id'], ['grading_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_attempt_id'], ['attempts.id'], name='fk_scenarios_source_attempt', ondelete='SET NULL', use_alter=True),
    sa.ForeignKeyConstraint(['template_id'], ['card_templates.id'], ),
    sa.ForeignKeyConstraint(['validated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.create_index('ix_scenarios_category_id', ['category_id'], unique=False)
        batch_op.create_index('ix_scenarios_difficulty', ['difficulty'], unique=False)
        batch_op.create_index('ix_scenarios_reference_card', ['reference_card'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_scenarios_status_origin', ['status', 'origin'], unique=False)

    op.create_table('training_sessions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.Enum('CARDS', 'CARD_ACTIONS', 'MIXED', name='session_mode'), nullable=False),
    sa.Column('question_source', sa.Enum('GENERATED', 'STUDENT', 'MIXED', name='question_source'), nullable=False),
    sa.Column('status', sa.Enum('PLANNED', 'RUNNING', 'FINISHED', 'CANCELLED', name='session_status'), nullable=False),
    sa.Column('grading_profile_id', sa.UUID(), nullable=True),
    sa.Column('difficulty_min', sa.SmallInteger(), nullable=False),
    sa.Column('difficulty_max', sa.SmallInteger(), nullable=False),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('settings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('difficulty_min <= difficulty_max', name='ck_training_sessions_difficulty_range'),
    sa.ForeignKeyConstraint(['grading_profile_id'], ['grading_profiles.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index('ix_training_sessions_group_id', ['group_id'], unique=False)
        batch_op.create_index('ix_training_sessions_status', ['status'], unique=False)
        batch_op.create_index('ix_training_sessions_teacher_id', ['teacher_id'], unique=False)

    op.create_table('attempts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ISSUED', 'IN_PROGRESS', 'SUBMITTED', 'EXPIRED', 'EVALUATED', name='attempt_status'), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('time_limit_sec', sa.Integer(), nullable=False),
    sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('evaluation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evaluated_by', sa.Enum('AI', 'EXPERT', 'HYBRID', name='evaluation_source'), nullable=True),
    sa.Column('evaluated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('expert_id', sa.UUID(), nullable=True),
    sa.Column('expert_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('expert_comment', sa.Text(), nullable=True),
    sa.Column('expert_reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= 100)', name='ck_attempts_score_range'),
    sa.ForeignKeyConstraint(['expert_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'user_id', 'seq')
    )
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.create_index('ix_attempts_answer', ['answer'], unique=False, postgresql_using='gin')
        batch_op.create_index('ix_attempts_scenario_id', ['scenario_id'], unique=False)
        batch_op.create_index('ix_attempts_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_attempts_status', ['status'], unique=False)
        batch_op.create_index('ix_attempts_submitted_at', ['submitted_at'], unique=False)
        batch_op.create_index('ix_attempts_user_id', ['user_id'], unique=False)

    op.create_table('certificates',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('number', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('issued_by', sa.UUID(), nullable=True),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.create_index('ix_certificates_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_certificates_user_id', ['user_id'], unique=False)

    op.create_table('insights',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('GROUP_TYPICAL_ERRORS', 'STUDENT_RECOMMENDATION', 'SESSION_SUMMARY', name='insight_kind'), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('target_user_id', sa.UUID(), nullable=True),
    sa.Column('target_group_id', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('ai_model', sa.String(length=64), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('target_user_id IS NOT NULL OR target_group_id IS NOT NULL OR session_id IS NOT NULL', name='ck_insights_has_target'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.create_index('ix_insights_session_kind', ['session_id', 'kind'], unique=False)
        batch_op.create_index('ix_insights_target_group_id', ['target_group_id'], unique=False)
        batch_op.create_index('ix_insights_target_user_id', ['target_user_id'], unique=False)

    op.create_table('reports',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('kind', sa.Enum('SESSION', 'STUDENT_PROGRESS', 'GROUP_PROGRESS', 'ERROR_HEATMAP', 'SYSTEM_USAGE', 'SECURITY_AUDIT', name='report_kind'), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'READY', 'FAILED', name='report_status'), nullable=False),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("format IN ('pdf', 'xlsx', 'csv', 'json')", name='ck_reports_format'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index('ix_reports_created_by', ['created_by'], unique=False)
        batch_op.create_index('ix_reports_session_id', ['session_id'], unique=False)
        batch_op.create_index('ix_reports_status_created', ['status', 'created_at'], unique=False)

    op.create_table('scenario_corrections',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('scenario_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('applied', sa.Boolean(), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['scenario_id'], ['scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scenario_corrections', schema=None) as batch_op:
        batch_op.create_index('ix_scenario_corrections_scenario_id', ['scenario_id'], unique=False)

    op.create_table('session_categories',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['incident_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'category_id')
    )
    with op.batch_alter_table('session_categories', schema=None) as batch_op:
        batch_op.create_index('ix_session_categories_category_id', ['category_id'], unique=False)

    op.create_table('session_participants',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['training_sessions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('session_id', 'user_id')
    )
    with op.batch_alter_table('session_participants', schema=None) as batch_op:
        batch_op.create_index('ix_session_participants_user_id', ['user_id'], unique=False)

    op.create_table('attempt_errors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('CONTENT', 'TIMING', 'GRAMMAR', 'PROCEDURE', 'MISSING', name='error_kind'), nullable=False),
    sa.Column('field_key', sa.String(length=64), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('expected', sa.Text(), nullable=True),
    sa.Column('actual', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.CheckConstraint('severity BETWEEN 1 AND 5', name='ck_attempt_errors_severity'),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attempt_errors', schema=None) as batch_op:
        batch_op.create_index('ix_attempt_errors_attempt_id', ['attempt_id'], unique=False)
        batch_op.create_index('ix_attempt_errors_kind_field', ['kind', 'field_key'], unique=False)

    op.create_table('calls',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.Enum('VOIP', 'TEXT', name='call_channel'), nullable=False),
    sa.Column('sip_call_id', sa.String(length=128), nullable=True),
    sa.Column('asterisk_channel', sa.String(length=256), nullable=True),
    sa.Column('caller_number', sa.String(length=32), nullable=True),
    sa.Column('status', sa.Enum('RINGING', 'ANSWERED', 'MISSED', 'FINISHED', name='call_status'), nullable=False),
    sa.Column('ring_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('answer_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finish_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('answer_delay_ms', sa.Integer(), nullable=True),
    sa.Column('rtt_ms', sa.Integer(), nullable=True),
    sa.Column('audio_path', sa.String(length=512), nullable=True),
    sa.Column('audio_format', sa.String(length=8), nullable=True),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['attempt_id'], ['attempts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_calls_asterisk_channel'), ['asterisk_channel'], unique=False)
        batch_op.create_index('ix_calls_attempt_id', ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_calls_sip_call_id'), ['sip_call_id'], unique=True)
        batch_op.create_index('ix_calls_status', ['status'], unique=False)

    op.create_table('call_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('call_id', sa.UUID(), nullable=False),
    sa.Column('author', sa.String(length=16), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("author IN ('caller', 'operator', 'system')", name='ck_call_messages_author'),
    sa.ForeignKeyConstraint(['call_id'], ['calls.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.create_index('ix_call_messages_call_id_created', ['call_id', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('call_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_call_messages_call_id_created')

    op.drop_table('call_messages')
    with op.batch_alter_table('calls', schema=None) as batch_op:
        batch_op.drop_index('ix_calls_status')
        batch_op.drop_index(batch_op.f('ix_calls_sip_call_id'))
        batch_op.drop_index('ix_calls_attempt_id')
        batch_op.drop_index(batch_op.f('ix_calls_asterisk_channel'))

    op.drop_table('calls')
    with op.batch_alter_table('attempt_errors', schema=None) as batch_op:
        batch_op.drop_index('ix_attempt_errors_kind_field')
        batch_op.drop_index('ix_attempt_errors_attempt_id')

    op.drop_table('attempt_errors')
    with op.batch_alter_table('session_participants', schema=None) as batch_op:
        batch_op.drop_index('ix_session_participants_user_id')

    op.drop_table('session_participants')
    with op.batch_alter_table('session_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_session_categories_category_id')

    op.drop_table('session_categories')
    with op.batch_alter_table('scenario_corrections', schema=None) as batch_op:
        batch_op.drop_index('ix_scenario_corrections_scenario_id')

    op.drop_table('scenario_corrections')
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index('ix_reports_status_created')
        batch_op.drop_index('ix_reports_session_id')
        batch_op.drop_index('ix_reports_created_by')

    op.drop_table('reports')
    with op.batch_alter_table('insights', schema=None) as batch_op:
        batch_op.drop_index('ix_insights_target_user_id')
        batch_op.drop_index('ix_insights_target_group_id')
        batch_op.drop_index('ix_insights_session_kind')

    op.drop_table('insights')
    with op.batch_alter_table('certificates', schema=None) as batch_op:
        batch_op.drop_index('ix_certificates_user_id')
        batch_op.drop_index('ix_certificates_session_id')

    op.drop_table('certificates')
    with op.batch_alter_table('attempts', schema=None) as batch_op:
        batch_op.drop_index('ix_attempts_user_id')
        batch_op.drop_index('ix_attempts_submitted_at')
        batch_op.drop_index('ix_attempts_status')
        batch_op.drop_index('ix_attempts_session_id')
        batch_op.drop_index('ix_attempts_scenario_id')
        batch_op.drop_index('ix_attempts_answer', postgresql_using='gin')

    op.drop_table('attempts')
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index('ix_training_sessions_teacher_id')
        batch_op.drop_index('ix_training_sessions_status')
        batch_op.drop_index('ix_training_sessions_group_id')

    op.drop_table('training_sessions')
    with op.batch_alter_table('scenarios', schema=None) as batch_op:
        batch_op.drop_index('ix_scenarios_status_origin')
        batch_op.drop_index('ix_scenarios_reference_card', postgresql_using='gin')
        batch_op.drop_index('ix_scenarios_difficulty')
        batch_op.drop_index('ix_scenarios_category_id')

    op.drop_table('scenarios')
    with op.batch_alter_table('group_members', schema=None) as batch_op:
        batch_op.drop_index('ix_group_members_user_id')

    op.drop_table('group_members')
    with op.batch_alter_table('user_service_scope', schema=None) as batch_op:
        batch_op.drop_index('ix_user_service_scope_category_id')

    op.drop_table('user_service_scope')
    with op.batch_alter_table('system_settings', schema=None) as batch_op:
        batch_op.drop_index('ix_system_settings_scope')

    op.drop_table('system_settings')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index('ix_refresh_tokens_user_id')
        batch_op.drop_index('ix_refresh_tokens_expires_at')

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('materials', schema=None) as batch_op:
        batch_op.drop_index('ix_materials_is_indexed')
        batch_op.drop_index('ix_materials_category_id')

    op.drop_table('materials')
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_index('ix_groups_teacher_id')

    op.drop_table('groups')
    with op.batch_alter_table('grading_profiles', schema=None) as batch_op:
        batch_op.drop_index('uq_grading_profiles_single_default', postgresql_where=sa.text('is_default'))
        batch_op.drop_index('ix_grading_profiles_owner_id')

    op.drop_table('grading_profiles')
    with op.batch_alter_table('backups', schema=None) as batch_op:
        batch_op.drop_index('ix_backups_started_at')

    op.drop_table('backups')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_log_user_ts')
        batch_op.drop_index('ix_audit_log_ts')
        batch_op.drop_index('ix_audit_log_object')
        batch_op.drop_index('ix_audit_log_action')

    op.drop_table('audit_log')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('uq_alerts_open_fingerprint', postgresql_where=sa.text("status <> 'RESOLVED'"))
        batch_op.drop_index('ix_alerts_status_severity')
        batch_op.drop_index('ix_alerts_last_seen_at')

    op.drop_table('alerts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_role_id')
        batch_op.drop_index('ix_users_is_active')

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('system_events', schema=None) as batch_op:
        batch_op.drop_index('ix_system_events_ts')
        batch_op.drop_index('ix_system_events_component_level')

    op.drop_table('system_events')
    op.drop_table('roles')
    op.drop_table('permissions')
    with op.batch_alter_table('incident_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_incident_categories_service_code')
        batch_op.drop_index('ix_incident_categories_parent_id')

    op.drop_table('incident_categories')
    with op.batch_alter_table('card_templates', schema=None) as batch_op:
        batch_op.drop_index('uq_card_templates_active_code', postgresql_where=sa.text('is_active'))

    op.drop_table('card_templates')
    # ### end Alembic commands ###
